### ISSUE TITLE
there is no way the content behind the overlay is intractable ? 

### ISSUE THREAD

**Issue by a-eid** [aspect-apps/react-navigation-overlay#2]
unlike react-native-navigations's overlay, this lib doesn't add a way to interact with the content behind it. 

please look up:  `interceptTouchOutside` 

https://wix.github.io/react-native-navigation/docs/overlay/

**Comment by lukebrandonfarrell** [comment]
@a-eid This lib is merely an API around the [react-native-modal](https://github.com/react-native-modal/react-native-modal) to give is an easy API to show overlays in React Navigation. You can pass any props that  [react-native-modal](https://github.com/react-native-modal/react-native-modal) accepts. The API is **inspired** by the [Overlay API](https://wix.github.io/react-native-navigation/docs/overlay/) in React Native Navigation.
